### ISSUE TITLE
inconsistencies in status-json.xsl

### ISSUE THREAD

**Issue by Yamakaky** [xiph/Icecast-Server#12]
- If there isn't any sources, json.icestats.source is not defined
- If there is one source, it's an object
- If there is 2+ sources, it's an array of object

That makes it harder to handle that it should be. I suggest always generating a "sources" key as an array of objects (empty if no sources).

Also, I forgot to record it but at one time the generated json wasn't valid. Don't you wan't to use a json lib? It should solve this point easily.

**Comment by ePirat** [comment]
This is not so easy to solve at the moment as the main and internally used format used is XML.

**Comment by phschafft** [comment]
The status-json.xsl was replaced by the publicstats interface. Therefore closing this ticket as it is about now legacy parts.
