### ISSUE TITLE
Compile from source documentation needs some improvements.

### ISSUE THREAD

**Issue by mgillespie** [xiph/Icecast-Server#13]
for example, mentioning to ensure that you clone recursively.  I spent hours trying to work out why the code wouldn't compile, and it was something as trivial as not cloning recursively....

**Comment by ePirat** [comment]
Which documentation are you referring to? The [wiki](https://wiki.xiph.org/Icecast_Server/Git_workflow) mentions this.

**Comment by mgillespie** [comment]
Never found that documentation, perhaps it's too well hidden?
I was using this, which has an install section.
https://github.com/xiph/Icecast-Server/blob/master/README.md

**Comment by ePirat** [comment]
Thank you, indeed that needs clarification. I will update it when I have time.

**Comment by ePirat** [comment]
Fixed by 9115d75
