### ISSUE TITLE
Feature Request : Support HTTP 2.0

### ISSUE THREAD

**Issue by Brahmasmi** [xiph/Icecast-Server#14]
As someone who is a layman user, I have no idea whether this feature request is relevant/applicable for Icecast.

I tried searching for an HTTP 2 feature request/issue, but was unable to find one. In case there is already a tracking issue or Icecast already implements HTTP 2.0 or there is a way to achieve this without changes in Icecast, I apologize for opening this issue.

Thanks.

**Comment by dm8tbr** [comment]
We don't use this tracker. Issues are tracked on https://gitlab.xiph.org

That aside, we did evaluate the possibility to move to HTTP2, but didn't find a suitable library so far, despite going through all the major projects and testing them.

**Comment by Brahmasmi** [comment]
Apologies for commenting on a closed issue, but I think there might be a good reason to reopen this one.

I just chanced upon chttp2, which seems to be Google's http 2.0 transport implementation used in gRPC.

https://github.com/grpc/grpc/tree/master/src/core/ext/transport/chttp2

Again, I am a layman, but I would assume that Google would have spent some time on the quality of the implementation, since it is the transport used by gRPC. Also, since gRPC is Apache 2 licensed, there should not be any problem in depending on chttp2. Again, I am not a lawyer.

@dm8tbr @ePirat @ph3-der-loewe

**Comment by ePirat** [comment]
There are much more important things than http2, I do not really see good usecases for new http2 features with Icecast to be honest.

**Comment by Brahmasmi** [comment]
Thank you @ePirat for your reply.

I understand that there might be more important things. May be in future, if and when @dm8tbr again evaluates alternatives for adopting HTTP 2.0, it might be useful to look at chttp2.
