### ISSUE TITLE
Icecast does not support HEAD requests

### ISSUE THREAD

**Issue by sideeffffect** [xiph/Icecast-Server#2]
Since Icecast does not support HEAD requests, it is not possible to play these streams using Aurora.js

https://github.com/audiocogs/aurora.js/issues/135
https://github.com/ampache/ampache/issues/933

**Comment by ePirat** [comment]
We are tracking this issue over at our [Trac], so I will close it here.

[Trac]: https://trac.xiph.org/ticket/2223
