### ISSUE TITLE
Possible bug with playlist.log

### ISSUE THREAD

**Issue by madprops** [xiph/Icecast-Server#23]
Not sure if it's a bug but I'm posting this anyway. I noticed a lot of frequent duplicates when checking playlist.log.

> 20/Feb/2018:12:07:37 -0500|/wok3n|1|MtH - 7MLGD
20/Feb/2018:12:11:04 -0500|/wok3n|1|emune - lifted
**20/Feb/2018:12:13:05 -0500|/wok3n|1|Gorillaz - On Melancholy Hill
20/Feb/2018:12:16:58 -0500|/wok3n|1|Gorillaz - On Melancholy Hill**
20/Feb/2018:12:16:59 -0500|/wok3n|1|nix - you  prod. alembic
20/Feb/2018:12:21:15 -0500|/wok3n|1|Orlando Díaz - Ser Sub
**20/Feb/2018:12:24:21 -0500|/wok3n|1|Veruca Salt - Victrola
20/Feb/2018:12:26:39 -0500|/wok3n|0|Veruca Salt - Victrola**
20/Feb/2018:12:26:40 -0500|/wok3n|0|Apollo Brown - Tao Te Ching
20/Feb/2018:12:28:42 -0500|/wok3n|1|Augustus Pablo - 555 Dub Street
20/Feb/2018:12:31:15 -0500|/wok3n|0|Rites of Spring - For Want Of
20/Feb/2018:12:34:17 -0500|/wok3n|0|kidkanevil - Shunkanido
20/Feb/2018:12:38:45 -0500|/wok3n|0|Animal Collective - Bluish
20/Feb/2018:12:43:58 -0500|/wok3n|0|THiNGYBOBinc - Jet Set Auradio
20/Feb/2018:12:45:57 -0500|/wok3n|0|Quickly, Quickly - Fog
**20/Feb/2018:12:49:21 -0500|/wok3n|0|J Dilla - Stepson of the Clapper
20/Feb/2018:12:50:12 -0500|/wok3n|0|J Dilla - Stepson of the Clapper**
20/Feb/2018:12:50:13 -0500|/wok3n|0|Gang Starr - Soliloquy Of Chaos
**20/Feb/2018:12:53:17 -0500|/wok3n|0|Nujabes - Music Is Mine
20/Feb/2018:12:57:27 -0500|/wok3n|0|Nujabes - Music Is Mine**
20/Feb/2018:12:57:27 -0500|/wok3n|0|My Bloody Valentine - Blown a Wish

Using 2.4.99.2

Source client is mpd.

**Comment by dm8tbr** [comment]
This is most likely your source client sending multiple metadata updates. Please open a bug with them instead. Nothing we can do, Icecast performs as designed.
