### ISSUE TITLE
Segmentation Fault in auth.c

### ISSUE THREAD

**Issue by hopejr** [xiph/Icecast-Server#24]
There is a seg fault on unlocking the thread on line 189 of auth.c in the function auth_release() under certain circumstances:
1. Configure a mount point with a fallback that is a relay from another server that is actually running (the stream must have parameter hidden=0 and fallback-override=1)
2. Start Icecast
3. Stream to Icecast, and then stop the stream after an arbitrary amount of time
4. Load the status page in the browser
At that point, there will be a seg fault as described above. It does not happen when the mount point is hidden for some reason.

Test system is running Debian 9.3. Icecast version 2.4.99.2

**Comment by ePirat** [comment]
As we track issues over at our Gitlab, I've posted your report there:

https://gitlab.xiph.org/xiph/icecast-server/issues/2330
