### ISSUE TITLE
Icecast kicks source 

### ISSUE THREAD

**Issue by TheGreyDiamond** [xiph/Icecast-Server#25]
When I open the status-json.xsl Icecast kicks the source at \test.mp3. I try to open the status-json.xsl because i'am making a little local website. Is this my problem? If yes, what did I wrong?

IceCast2 Infos:
server_id	Icecast 2.4.2

**Comment by ePirat** [comment]
Can’t reproduce this problem, please provide logs (`error.log` in Verbose mode ideally).
