### ISSUE TITLE
Multi cores for Icecast 

### ISSUE THREAD

**Issue by inetactief** [xiph/Icecast-Server#30]
Hi,

How can use multi cores for Icecast? Now we see one proc using one core. 

Best regards,
Michel

**Comment by dm8tbr** [comment]
Icecast is multi-threaded. If run on a machine with multiple cores its threads *should* utilize them. Some threads do more than others though, so load will most likely not spread evenly. In most usage scenarios you will run out of network bandwidth before CPU usage becomes relevant.

> Should you have questions about Icecast setup, we recommend to join the Icecast users mailing list:
> http://lists.xiph.org/mailman/listinfo/icecast
> After signing up you can send your questions to icecast@xiph.org and will receive answers by email.

**Comment by bw-development** [comment]
From this point of view how tuning for example FreeBSD/Debian to force icecast2 utilizing multiple cores in multi-CPU systems (2/4/6 CPUs) ? Thank You!

**Comment by bw-development** [comment]
P.S. Is this more linked to "BIOS-motherboard-CPU" or "CPU-operating system" chain ?
