### ISSUE TITLE
Wrong port passed to URL authentication when listening on both :80 and :443

### ISSUE THREAD

**Issue by bradisbell** [xiph/Icecast-Server#32]
Suppose I have an Icecast server listening for HTTP on port 80, and HTTPS on port 443.

When I connect to a stream via HTTPS, the `port` parameter sent to a `listener_add` URL-based authentication handler indicates port 80 in the POST data.  I'd expect it to indicate port 443.

**Comment by phschafft** [comment]
See https://gitlab.xiph.org/xiph/icecast-server/-/issues/2435.
