### ISSUE TITLE
Setting any stream metadata field to - invalidates json in status-json.xsl

### ISSUE THREAD

**Issue by kid-c-plus** [xiph/Icecast-Server#34]
As title. When I set any field in the stream info to a single -, the data displays properly on the status.xsl page, but the dash is not placed in quotes in the status-json.xsl page and the resulting data cannot be parsed.
![Screen Shot 2020-04-29 at 11 53 51 AM](https://user-images.githubusercontent.com/17421375/80623772-4fbb3480-8a10-11ea-9fbf-23ece2a2132b.png)

**Comment by hairmare** [comment]
It looks like this bug was fixed in v2.5.0-beta.2 with https://github.com/xiph/Icecast-Server/commit/56bbc0d12cbead128919031e26ea661e8c0b8874.

**Comment by kid-c-plus** [comment]
must've missed that, thanks!
