### ISSUE TITLE
JSON status encoding modification

### ISSUE THREAD

**Issue by yiann0s** [xiph/Icecast-Server#39]
Below you will find an excerpt from json status response of broadcast server (status-json.xsl). Original title of song is "オンライン博物館 INTERNET 1.0 Log on". Can I modify server files so that the encoding of the metadata is based in utf8 ? I have a problem with songs with greek/ japanese characters.
`name","server_type":"audio/mpeg","server_url":"https://www.mixxx.org","stream_start":"Sat, 07 Nov 2020 20:46:58 +0000","stream_start_iso8601":"2020-11-07T20:46:58+0000",**"title":"CYBEREALITY??? - ???????? INTERNET 1.0 Log`**

**Comment by phschafft** [comment]
You are depending here on two legacy technologies:
* ICY, which does not support charsets at all
* status-json.xsl (which was replaced in 2.5.x, is still valid for 2.4.x)

As ICY does not support charset parameters there is hardly anything Icecast can do about this.

That said there have been a few updates here in abfd3c51a3260f6f3df2d0da10e47621674ab533. They might help or.. not. It also depends a lot on the source client to send what is expected (which might or might not be what is correct).

If there is really a bug, feel free to open a ticket in the official bug tracker at https://gitlab.xiph.org/xiph/icecast-server/-/issues.
