### ISSUE TITLE
Icecast stream not working on Safari

### ISSUE THREAD

**Issue by Ceel0** [xiph/Icecast-Server#40]
Hello guys,

I hope you're well. I have an issue with my Web radio. Users using Safari can't stream the radio. All is working perfectly with other web browsers.

When i navigate on my icecast URL, player for the mountpoint is missing with Safari.

Do you have any idea ?

Icecast version : 2.4.99.2
OS version : Debian 9

BR,

Ceelo

**Comment by JamieWhite** [comment]
Are you streaming in `.ogg`? If so that's your problem as Safari doesn't support it. You'll need to use another encoding like `.aac`

**Comment by phschafft** [comment]
ping?

**Comment by phschafft** [comment]
Closing the ticket for missing infos + inactivity.
