### ISSUE TITLE
max listeners per one mountpoint?

### ISSUE THREAD

**Issue by cybicz** [xiph/Icecast-Server#49]
Hi, it looks like, there is limit for 20000 concurrent users per one mountpoint. Is that correct?

Thanks

Icecast 2.4.4

**Comment by phschafft** [comment]
There is no limit. However you might run out of resources at some point. Resources might be hardware but also e.g. file handles or TCP ports. While > 20k listeners is possible (and tested!) it should not be done in real deployments as it tends to fall apart randomly for reasons outside of Icecast (such as the OS, hardware, data center connectivity,...). Generally the recommendation is planing for 10k listeners per node and configuring a limit of 15k listeners so alive nodes can catch listeners dropped by dead nodes of a cluster in case of maintenance/failure.
