### ISSUE TITLE
Not able to clone "Connection timed out" Error

### ISSUE THREAD

**Issue by mylselgan** [xiph/Icecast-Server#50]
Relay-1:~# git clone --recursive https://git.xiph.org/icecast-server.git
Cloning into 'icecast-server'...
fatal: unable to access 'https://git.xiph.org/icecast-server.git/': Failed to connect to git.xiph.org port 443: Connection timed out

Relay-1:~# git clone --recursive http://git.xiph.org/icecast-server.git
Cloning into 'icecast-server'...
fatal: unable to access 'http://git.xiph.org/icecast-server.git/': Failed to connect to git.xiph.org port 80: Connection timed out

Relay-1:~# git clone http://git.xiph.org/icecast-server.git
Cloning into 'icecast-server'...
fatal: unable to access 'http://git.xiph.org/icecast-server.git/': Failed to connect to git.xiph.org port 80: Connection timed out

**Comment by mylselgan** [comment]
finally cloned from git clone --recursive https://gitlab.xiph.org/xiph/icecast-server.git.
update the read me file accordingly or fix the connectivity issue

**Comment by rillian** [comment]
git.xiph.org is no longer online. I've updated the readme.

Thanks for the report!
