### ISSUE TITLE
JSON stats http url not automatically redirecting to secure https

### ISSUE THREAD

**Issue by sanderdewijs** [xiph/Icecast-Server#53]
For some reason the JSON stats URL is not redirecting all trafic to the https version. If I visit http://spiritueelsamen.nl:8002/status-json.xsl I see an error that the page has been re-initialized.

When I visit https://spiritueelsamen.nl:8002/status-json.xsl the stats page is shown correctly. Is there some way to change this behaviour?

**Comment by phschafft** [comment]
This has been fixed in 7742bf0a217dcdbb98814742b575bd2cc1930e0e long ago. Please try to upgrade if that is needed.
Also keep in mind:
* for the listen URL to be valid for a given user the stats documents must be fetched the same way (read: by said user).
* the status-json.xsl was deprecated in 2.5.x

**Comment by sanderdewijs** [comment]
The reason for posting this issue was because I want to see the listener stats of the IceCast stream in Sam broadcaster Pro. The statistic relay settings in SAMBC require a valid user / password to fetch the stats from the server. If the status-json.xsl was deprecated in 2.5.x, what would be the correct URL/endpoint to fetch the stats from the server?

**Comment by phschafft** [comment]
The correct endpoints are `/admin/stats` (for access by admin, and source), and `/admin/publicstats` (for everyone). As always both accepting the `mount` parameter (which you really want to use when only fetching data for a single source).

PS: It's Icecast, not IceCast. ;)
