### ISSUE TITLE
Artist, title and album all together

### ISSUE THREAD

**Issue by roughnecks** [xiph/Icecast-Server#57]
Hello,

sorry if I can't explain this very well but when I'm listening to my Icecast stream in foobar2000, metadata is all in the title section, so I get artist, title and album all together under title.

I'm streaming to the server using ezstream and I tried searching for clues but I just don't know who the fault is and if is there a fix..

Thanks

**Comment by phschafft** [comment]
This sounds like you're using a legacy format like MP3 or AAC. Those formats simply do not support anything else but "StreamTitle". All other formats support full metadata.

Please confirm which format you are using. If it is MP3 or AAC there is simply nothing that can be done about it as it is a limitation of those formats, not of Icecast.

**Comment by roughnecks** [comment]
Yeah, using MP3. Thanks
