### ISSUE TITLE
Icecast xml problem

### ISSUE THREAD

**Issue by PythonSnake-lang** [xiph/Icecast-Server#60]
Hi, i am currently using icecast on windows and whenever i try to edit the XML config it says that (After i try to save) im not the owner so can anyone help?

**Comment by phschafft** [comment]
This sounds much more like permission problem with the file. Maybe the file was created by a different user?

Also please note that this is not the official ticket system for the project.

**Comment by PythonSnake-lang** [comment]
nvm i just needed to update

**Comment by PythonSnake-lang** [comment]
nvm i just needed to update
