### ISSUE TITLE
Icecast to accept custom REMOTE IP headers for reverse proxy compatibility.

### ISSUE THREAD

**Issue by mautematico** [xiph/Icecast-Server#9]
¡Hola!

There is already a ticket for this, but it seems unatended or low priority.
https://trac.xiph.org/ticket/1959

**Comment by ePirat** [comment]
Given that there is already a ticket for this, no need to report it again.

**Comment by mautematico** [comment]
Is there a way I can help on getting this done?
For the track progress, I think things are going on the right direction. On the other hand, things seems to be just nowhere on this ticket.

You just answered this github issue within a few days, but that track ticket has six+ weeks without activity (last activity was mine, in fact).

**Comment by mautematico** [comment]
Is there a way I can help on getting this done?
For the track progress, I think things are going on the right direction. On the other hand, things seems to be just nowhere on this ticket.

You just answered this github issue within a few days, but that track ticket has six+ weeks without activity (last activity was mine, in fact).

**Comment by ePirat** [comment]
Please write to the icecast-dev mailing list, thats the best thing you can do, to get in touch with the team. Alternatively you can visit our IRC channel, #icecast on Freenode.

**Comment by netmikey** [comment]
What is the official ticket tool for icecast? If it's github, I believe it would be cool if this would be tracked here. If not, you may want to disable the ticket feature for this repo and document where interested ppl should head to :)

On the topic: we have high needs for such a feature because we need TLS-encrypted audio streams. A reverse proxy could handle TLS termination, but we can't track client IPs when we try that. Since browsers and devices (Smartphones, Amazon's FireTV etc.) are deprecating plain http connections, I guess a lot of users will soon find they'll need this pretty quickly. May I suggest you reopen / reschedule this ticket?

**Comment by ePirat** [comment]
@netmikey The link to the official bugreporter ticket can be found in the first comment. 

Any reason you can't use Icecasts TLS support?

**Comment by netmikey** [comment]
Because we're using an Icecast Plugin from an Ad Marketer that intercepts streams and sends out ads in-stream, but this technology doesn't work with Icecast-encrypted streams.

**Comment by ePirat** [comment]
Thats a very weird thing to do, honestly. Any reason this tool is not just using Icecast fallbacks to do that? Anyway, back to the topic: There are very few people working on Icecast and right now most are busy with other things, therefore there was no update on this ticket for such a long time.

**Comment by netmikey** [comment]
I don't know the internals of that plugin, really, but my understanding is that it is pretty widely used for targeted audio marketing. I'll try to forward this ticket to their tech team, maybe they can shed some light on the issue or maybe even contribute the initial reverse proxy support :) anyway, thanks for the quick replies!

**Comment by mautematico** [comment]
@netmikey please forward this *and* the original track ticket to your team, there they will find some proposals for the initial reverse proxy.

in fact, there is a project karlheyes/icecast-kh that has already implemented it (xiph's track in fact references KH's implementation); tought it would be absolutely useful to have it implemented here on xiph/Icecast-Server, I think.

**Comment by AppWerft** [comment]
I tried this solution: https://stackoverflow.com/questions/51786404/icecast2-running-under-nginx-not-able-to-connect
Unfortunatelly the folder of submodule https://github.com/xiph/Icecast-Server/tree/master/src is emty.
The command git clone --recursively failed.
The sibling repo Icemaster-common doesn't fit.
